#:schema node_modules/wrangler/config-schema.json
name = "podter-url-shortener"
compatibility_date = "2024-07-12"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "KV"
id = "a85a597b84c34bdebb47924a340a1d48"
